### ISSUE TITLE
Please check plugin uniqueness

### ISSUE THREAD

**Issue by pcav** [dayjournal/qgis-attributeassignment-plugin#2]
There are various plugins that do similar things, e.g.
http://plugins.qgis.org/plugins/attributePainter/
http://plugins.qgis.org/plugins/quick_attribution/
http://plugins.qgis.org/plugins/AutoFields/
etc., see http://plugins.qgis.org/search/?q=attribute
Please check them and see if your plugin could be an extension of those, merging your work.
I'm sorry to bother, but we try hard not to duplicate functions, and to keep the number of plugins from increasing when not strictly necessary.

**Comment by dayjournal** [comment]
http://plugins.qgis.org/plugins/attributePainter
For this plugin the functions are similar but the behavior seems to be slightly different.

http://plugins.qgis.org/plugins/quick_attribution/
http://plugins.qgis.org/plugins/AutoFields/
It seems that the functions of these two plugins are different.

**Comment by pcav** [comment]
thanks for the review. There may be more similar plugins.
Would you mind discussing with the author of http://plugins.qgis.org/plugins/attributePainter the possibility of merging both works?
In any case, a note about these differences will be useful if added to the About.

**Comment by dayjournal** [comment]
OK.

**Comment by dayjournal** [comment]
http://plugins.qgis.org/plugins/attributePainter
It merged the missing features.

**Comment by pcav** [comment]
Sorry, I do not see your commits here: https://github.com/enricofer/attributepainter/commits/master
So your plugin is now a duplicate of exixting functionality? Please clarify.
Thanks.

**Comment by dayjournal** [comment]
I'm sorry, Please look at the link of the closed issue.
https://github.com/enricofer/attributepainter/issues/10

**Comment by pcav** [comment]
I see, thanks for clarifying. So your plugin is now redundant?

**Comment by dayjournal** [comment]
That's right. It is not necessary to register in the repository.
I will leave it only in this repository.
Thanks.

**Comment by pcav** [comment]
Great, thanks!
