### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by davidbelliveau** [dayjournal/qgis-attributeassignment-plugin#5]
I would like to have to value field have the option of auto-increment. That way, every time I click a new object, the value field would be incremented.

As it is, AttributeAssignment plugin is saving me a whole lot of time, but if it had an auto-incrementing option, I'd save more time...by an order of magnitude.

**Comment by dayjournal** [comment]
Hi,
Proposed Thank you.
Can you send me a pull requests?
