### ISSUE TITLE
Using configured edit widget

### ISSUE THREAD

**Issue by m-kuhn** [dayjournal/qgis-attributeassignment-plugin#6]
This plugin is very helpful to quickly change attributes.
It would be very nice to be able to use the configured edit widget instead of just plain text. This would allow to use comboboxes, date widgets and much more.

Would this be something that is desirable and that has the potential to be integrated here?

**Comment by dayjournal** [comment]
Hi,
Thanks for the suggestion.
Can you send me a pull request for suggestions?
I would like to consider it.

**Comment by m-kuhn** [comment]
Hi @dayjournal 

Pull request #7 includes the proposed changes. Please let me know if I need to adjust something.

**Comment by dayjournal** [comment]
@m-kuhn 

Hi,
I made it to the latest branch that contains the UI files.
Please make another pull request to the dev branch.
We do not want to change the method of converting UI files to Py files.

[dev branch](https://github.com/dayjournal/AttributeAssignment/tree/dev)

**Comment by dayjournal** [comment]
Close the issue and pull request.
